# -*- coding: utf-8 -*-
"""Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llaNkB779NE1iEiOvRJohAlmgfLDk2ld

# **Instructions for Dataset Setup**

To run this notebook, you need to first download the dataset from the shared Google Drive link:

[Shared Melanoma Dataset](https://drive.google.com/drive/folders/1kLYAv9jxFuBII54V8XChU7i9a2x-wLAC)

Steps:

Click the link above to open the shared folder.
Download the train and test folders to your own Google Drive.
Create a folder named melanoma in your Drive, and place the downloaded train and test folders inside it.
After this, the notebook will automatically use the following paths:



*   train_dir = "/content/drive/MyDrive/melanoma/train"
*   val_dir   = "/content/drive/MyDrive/melanoma/test"
*   save_model_dir = "/content/drive/MyDrive/melanoma/vit_skin_model"

# **Connect to Google Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Training**"""

# --------------------------------------
# Minimal ViT Training Functional
# --------------------------------------
import os, time
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from torchvision import transforms
from transformers import AutoImageProcessor, AutoModelForImageClassification, pipeline
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
import numpy as np
from tqdm import tqdm

# ---------- Paths ----------
train_dir = "/content/drive/MyDrive/melanoma/train"
val_dir   = "/content/drive/MyDrive/melanoma/test"
save_model_dir = "/content/drive/MyDrive/melanoma/vit_skin_model"

# ---------- Dataset ----------
class SkinDataset(Dataset):
    def __init__(self, img_dir, transform=None):
        self.img_paths, self.labels = [], []
        self.transform = transform
        for label, folder in enumerate(["benign", "malignant"]):
            folder_path = os.path.join(img_dir, folder)
            if not os.path.exists(folder_path):
                raise ValueError(f"Folder not found: {folder_path}")
            for img_file in os.listdir(folder_path):
                self.img_paths.append(os.path.join(folder_path, img_file))
                self.labels.append(label)
    def __len__(self): return len(self.img_paths)
    def __getitem__(self, idx):
        img = Image.open(self.img_paths[idx]).convert("RGB")
        if self.transform: img = self.transform(img)
        return img, torch.tensor(self.labels[idx])

# ---------- Transformations & DataLoader ----------
processor = AutoImageProcessor.from_pretrained("Kuldeepmishra3/vit-large-skin-cancer-ham10000")
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),  # Must match model input
    transforms.ToTensor(),
    transforms.Normalize(mean=processor.image_mean, std=processor.image_std)
])

train_loader = DataLoader(SkinDataset(train_dir, transform=preprocess), batch_size=2, shuffle=True)
val_loader   = DataLoader(SkinDataset(val_dir, transform=preprocess), batch_size=2)

# ---------- Load ViT-large ----------
model = AutoModelForImageClassification.from_pretrained(
    "Kuldeepmishra3/vit-large-skin-cancer-ham10000",
    num_labels=2,
    ignore_mismatched_sizes=True,
    from_tf=False
)

# Fine-tune only the classifier
for p in model.parameters(): p.requires_grad = False
for p in model.classifier.parameters(): p.requires_grad = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# ---------- Training (1 Epoch) ----------
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.classifier.parameters(), lr=1e-5)
epochs = 1

for epoch in range(epochs):
    start_epoch = time.time()
    model.train()
    total_loss = 0
    for imgs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} - Training"):
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(imgs).logits
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader)

    # Validation
    model.eval()
    all_labels, all_preds, all_probs = [], [], []
    for imgs, labels in tqdm(val_loader, desc=f"Epoch {epoch+1}/{epochs} - Validation"):
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs).logits
        probs = torch.softmax(outputs, dim=1)[:,1]
        preds = torch.argmax(outputs, dim=1)
        # detach to numpy
        all_labels.extend(labels.cpu().detach().numpy())
        all_preds.extend(preds.cpu().detach().numpy())
        all_probs.extend(probs.cpu().detach().numpy())

    all_labels, all_preds, all_probs = np.array(all_labels), np.array(all_preds), np.array(all_probs)

    # Metrics
    acc = (all_preds==all_labels).mean()
    precision = precision_score(all_labels, all_preds)
    recall = recall_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds)
    conf_matrix = confusion_matrix(all_labels, all_preds)
    try:
        roc_auc = roc_auc_score(all_labels, all_probs)
    except:
        roc_auc = float('nan')

    elapsed = time.time() - start_epoch
    print(f"Epoch {epoch+1} completed in {elapsed:.1f}s | Loss: {avg_loss:.4f} | Accuracy: {acc:.4f} | Precision: {precision:.4f} | Recall: {recall:.4f} | F1-score: {f1:.4f} | ROC/AUC: {roc_auc:.4f}")
    print("Confusion Matrix:\n", conf_matrix)

# ---------- Save Model ----------
os.makedirs(save_model_dir, exist_ok=True)
model.save_pretrained(save_model_dir)
processor.save_pretrained(save_model_dir)
print("Model saved at:", save_model_dir)

# ---------- Prediction Pipeline ----------
classifier = pipeline("image-classification", model=save_model_dir, feature_extractor=save_model_dir)
# result = classifier("/content/drive/MyDrive/proyecto - transformer/nuevo_lunar.jpg")
# print(result)

"""# **Confusion Matrix as Heatmap**"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Suponiendo que all_labels y all_preds ya están calculados
cm = confusion_matrix(all_labels, all_preds)
labels = ["benign", "malignant"]  # Nombres de tus clases

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.title('Confusion Matrix')
plt.show()

"""# **ROC Curve**"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# all_labels: etiquetas verdaderas
# all_probs: probabilidades de clase positiva

fpr, tpr, thresholds = roc_curve(all_labels, all_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, color='blue', lw=2, label=f'AUC = {roc_auc:.3f}')
plt.plot([0,1], [0,1], color='orange', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - ViT')
plt.legend(loc='lower right')
plt.show()

"""# **Verification / Prediction**"""

# ---------- Verification / Prediction Block ----------
from google.colab import files
from transformers import pipeline

# ---------- Load pipeline ----------
classifier = pipeline(
    "image-classification",
    model="/content/drive/MyDrive/melanoma/vit_skin_model",
    feature_extractor="/content/drive/MyDrive/melanoma/vit_skin_model"
)

# ---------- Class mapping ----------
class_map = { "LABEL_0": "benign", "LABEL_1": "malignant" }

# ---------- Upload image ----------
uploaded = files.upload()  # Se abre diálogo para seleccionar imagen
for filename in uploaded.keys():
    print(f"Image uploaded: {filename}")

    # ---------- Prediction ----------
    result = classifier(filename)

    # Map label
    label_raw = result[0]['label']
    label = class_map.get(label_raw, label_raw)
    score = result[0]['score']

    print(f"The model predicts this lesion as {label.upper()} with confidence {score*100:.2f}%")

# ---------- Verification / Prediction Block ----------
from google.colab import files
from transformers import pipeline

# ---------- Load pipeline ----------
classifier = pipeline(
    "image-classification",
    model="/content/drive/MyDrive/melanoma/vit_skin_model",
    feature_extractor="/content/drive/MyDrive/melanoma/vit_skin_model"
)

# ---------- Class mapping ----------
class_map = { "LABEL_0": "benign", "LABEL_1": "malignant" }

# ---------- Upload image ----------
uploaded = files.upload()  # Se abre diálogo para seleccionar imagen
for filename in uploaded.keys():
    print(f"Image uploaded: {filename}")

    # ---------- Prediction ----------
    result = classifier(filename)

    # Map label
    label_raw = result[0]['label']
    label = class_map.get(label_raw, label_raw)
    score = result[0]['score']

    print(f"The model predicts this lesion as {label.upper()} with confidence {score*100:.2f}%")

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from transformers import AutoModelForImageClassification
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
import numpy as np
import os
import pandas as pd

# ---------- Paths ----------
test_dir = "/content/drive/MyDrive/melanoma/test"
save_model_dir = "/content/drive/MyDrive/melanoma/vit_skin_model"

# ---------- Dataset ----------
class SkinDataset(Dataset):
    def __init__(self, img_dir, transform=None):
        self.img_paths, self.labels = [], []
        self.transform = transform
        for label, folder in enumerate(["benign","malignant"]):
            folder_path = os.path.join(img_dir, folder)
            for img_file in os.listdir(folder_path):
                self.img_paths.append(os.path.join(folder_path, img_file))
                self.labels.append(label)
        self.transform = transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img = Image.open(self.img_paths[idx]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img, torch.tensor(self.labels[idx])

# ---------- Transform ----------
preprocess = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # Standard ImageNet normalization
])

test_loader = DataLoader(SkinDataset(test_dir, transform=preprocess), batch_size=2)

# ---------- Load model ----------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForImageClassification.from_pretrained(
    save_model_dir,
    num_labels=2,
    ignore_mismatched_sizes=True,
    from_tf=False
)
model.to(device)
model.eval()

# ---------- Evaluate ----------
y_true, y_pred, y_prob = [], [], []

with torch.no_grad():
    for imgs, labels in test_loader:
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs).logits
        probs = torch.softmax(outputs, dim=1)[:,1]  # probability of class 1
        preds = torch.argmax(outputs, dim=1)
        y_true.extend(labels.cpu().numpy())
        y_pred.extend(preds.cpu().numpy())
        y_prob.extend(probs.cpu().numpy())

# ---------- Metrics ----------
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
roc_auc = roc_auc_score(y_true, y_prob)
total_params = sum(p.numel() for p in model.parameters())

df_results = pd.DataFrame([{
    "Model": "ViT-large",
    "Accuracy (%)": round(accuracy*100,2),
    "F1-Score (%)": round(f1*100,2),
    "Precision (%)": round(precision*100,2),
    "Recall (%)": round(recall*100,2),
    "ROC/AUC": round(roc_auc,4),
    "Total Parameters": total_params
}])

print(df_results)